version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static
    depends_on:
      - app

  db:
    image: postgres
    ports:
    - "5433:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  app:
    build: ./docker
    #command: python3 manage.py runserver 0.0.0.0:8000
    command: uwsgi --socket :8001 --module onlineSalon.wsgi
    volumes:
    - ./src:/code
    expose:
      - 8001
    depends_on:
      - db

volumes:
  postgres_data: