version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/gunicorn.conf:/etc/nginx/conf.d/default.conf
      - ./src/static:/static/static
      - gunicorn:/var/run/gunicorn
    depends_on:
      - app

  db:
    image: postgres
    ports:
    - "5433:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  app:
    build: ./docker
    #command: python3 manage.py runserver 0.0.0.0:8000
    command: gunicorn onlineSalone.wsgi:application --bind=unix:/var/run/gunicorn/gunicorn.sock
    volumes:
    - ./src:/code
    - gunicorn:/var/run/gunicorn
    ports:
    - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:

  gunicorn:
    driver: local