version: '3'

services:
  db:
    image: postgres
    ports:
    - "5433:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  app:
    build: ./docker
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
    - ./src:/code
    ports:
    - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: